#!/usr/bin/env bash
# script that transfers a file from our client to a server

# check if number of passed arguments is valid
if [ "$#" -ne 4 ]; then
   echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
   exit 1
fi

# copy/upload the file to remote server
scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~/.
