#!/bin/env bash
# This script terminates a process created by the file 4-to_infinity_and_beyond

# Find the PID of the process
pid=$(pgrep -f "4-to_infinity_and_beyond")

# Check if the process is running
# first check the length of the value stored in pid is not zero
if [ -n "$pid" ]; then
    # Send a SIGTERM signal to the process to terminate gracefully
    kill "$pid"

fi
