#!/usr/bin/env bash
# This script displays:

# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed (refer to the example)
# Requirements:

# You must use the for loop (while and until are forbidden)
# Do not display hidden files

for file in "$(ls .)"*; do
    filename="${file#*-}";
    echo "$filename";
done
